name: nice
description: Code generation for nice mocktail mocks.
version: 0.0.1
repository: https://github.com/jtdLab/nice
issue_tracker: https://github.com/jtdLab/nice/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  nice_annotation: ^0.0.1
  source_gen: ^1.2.3
  logging: ^1.1.1

dev_dependencies:
  test: ^1.21.0
